# Generated by Django 3.2 on 2023-05-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_rating'),
        ('reviews', '0003_review_unique_title_author'),
    ]

    operations = [
    ]
